services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"  
      - "2222:22"
    volumes:
      - ./laravel:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf  
    working_dir: /var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "2206:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  dbdata: